---
apiVersion: v1
kind: Secret
metadata:
  name: loki-multi-tenant-proxy-auth-config
  namespace: grafana
  labels:
    app: loki-multi-tenant-proxy
stringData:
  authn.yaml: |-
    users:
      - username: Tenant1
        password: 1tnaneT
        orgid: tenant-1
      - username: Tenant2
        password: 2tnaneT
        orgid: tenant-2
---
apiVersion: v1
kind: Service
metadata:
  name: loki-multi-tenant-proxy
  namespace: grafana
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki-multi-tenant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki-multi-tenant-proxy
  name: loki-multi-tenant-proxy
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-multi-tenant-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: loki-multi-tenant-proxy
    spec:
      containers:
      - name: loki-multi-tenant-proxy
        image: angelbarrera92/loki-multi-tenant-proxy:dev
        args:
          - "run"
          - "--port=3100"
          - "--loki-server=http://loki.grafana.svc.cluster.local:3100"
          - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
        ports:
          - name: http
            containerPort: 3100
            protocol: TCP   
        resources: {}
        volumeMounts:
          - name: config
            mountPath: /etc/loki-multi-tenant-proxy
      volumes:
        - name: config
          secret:
            secretName: loki-multi-tenant-proxy-auth-config
